### ISSUE TITLE
Crontab job doesn't stop after quitting the Django Server.

### ISSUE THREAD

**Issue by tanishqvyas** [kraiz/django-crontab#110]
#### Environment & Versions
* Operating system: Ubuntu 18.04
* Python: 3.7
* Django: 3.0.4
* django-crontab: 0.7.1

#### Settings
* My `django-crontab` settings: 
```python
CRONJOBS = [

    ('* * * * *','customer.mail_subscriber.info')
]

```

#### Details
* Output of `crontab -l` after running `python manage.py crontab add`.
```
* * * * * /home/tanishq/MonitorCorona/WebsiteCorona/bin/python3 /home/tanishq/MonitorCorona/WebsiteCorona/backend/manage.py crontab run 6965f107a037d8997e8f90ff0c4f6774 # django-cronjobs for backend
...
```
* If this output contained a `crontab run` command and I copy this command to my terminal the job works: No, it says     backend: Command not found

The script runs for sending emails to all the people present in the database after every minute. When I closed the server by pressing CONTROL+C and closed my chrome tabs, it still kept on sending emails. In the end i had to change the function to :

```
def info():
    pass
```

from old version
```
def info():
	import smtplib
	from email.mime.text import MIMEText

	# from .models import Customer

	server = smtplib.SMTP('smtp.gmail.com',587)
	server.ehlo()
	server.starttls()
	server.login('mymail@gmail.com', 'password')

	mail_list = []
	entries = list(Customer.objects.all().only("email"))
	mail_list = entries.copy()





	for mailid in mail_list:

		fromx = 'mymail@gmail.com'
		msg = MIMEText('I love Crontabs')
		msg['Subject'] = 'Corona Cases Updates'
		msg['From'] = fromx
		msg['To'] = mailid.email

		server.sendmail(fromx, mailid.email, msg.as_string())

	server.close()
```

Why does it not stop once the server is closed ? Is there any fix to this ?

**Comment by zzulu** [comment]
Cron is added to your OS(in your case, Ubuntu) side, so it doesn't related to your django server.
If you want to stop your cronjobs, use command `python manage.py crontab remove`.

**Comment by tanishqvyas** [comment]
@zzulu Thank You for helping
