### ISSUE TITLE
Crontab does not work when running server

### ISSUE THREAD

**Issue by Nour-Elgeziry** [kraiz/django-crontab#117]
When. ever i run the command python manage.py crontab run (job hash) it works but only for once abd not every minute as i se it up. I am looking for a way to make the job run every minute automatically whenever i run the server. I followed this documentation https://pypi.org/project/django-crontab/ and watched a YT tutorial , works for the guy , but for me just nothing happens as if there are no jobs to run. Thank you in advance and i am happy to provide any additional requirements. 

#### Environment & Versions
* Operating system: mac catalina
* Python:3.8.5
* Django:3.1.2
* django-crontab:0.7.1

#### Settings
* My `django-crontab` settings: 
```python
CRONJOBS = [
('* * * * *', 'shoppingCart.cron.test')
  ...
]
```

#### Details
* Output of `crontab -l` after running `python manage.py crontab add`.
*/1 * * * * /Users/nourelgeziry/.local/share/virtualenvs/Equal_Distribution_maintainance-M-bcKwQz/bin/python /Users/nourelgeziry/Desktop/MyProjects/Equal Distribution maintainance/EDMS/manage.py crontab run bd84e5bec9ad4805b334e11fafec1b5c # django-cronjobs for EDMS
```
...
```
* If this output contained a `crontab run` command and I copy this command to my terminal the job works: yes/no
yes

**Comment by vimox-shah** [comment]
facing the same issue

**Comment by Nour-Elgeziry** [comment]
No answers were provided

**Comment by giuseppenovielli** [comment]
MacOs Catalina not run job! @Nour-Elgeziry  Please re open this issue!

**Comment by giuseppenovielli** [comment]
HI @vimox-shah @Nour-Elgeziry please add into settings.py logging dictonary.
Watch this video -> https://www.youtube.com/watch?v=8Ujs7AyE2as

Working with macOs Catalina!
