### ISSUE TITLE
importerror no module named  myapp.cron

### ISSUE THREAD

**Issue by maloneguo** [kraiz/django-crontab#20]
i set my env and script as README.rst
and my task in cron.py like:
```
...
...
def task1():
      log.info("i 'm task 1");#log msg to a file
```
when i run(i'm in vritual env)
```python manage.py crontab add```
and there is nothing occured
i checked linux env with command "crontab -e", it shows like 
```
*/2 * * * *　/myvirtualenv/bin/python /myworkpath/manage.py crontab  run  c3a5f648ad78e794a12c664a
```
then i type `/myvirtualenv/bin/python /myworkpath/manage.py crontab  run  c3a5f648ad78e794a12c664a`directly in terminal  it's shows:
```
...
...
Importerror :no module named  myapp.cron
```
it's confused me ,what's root issue ?

**Comment by maloneguo** [comment]
i found the issue:
at the line of 124 ```import_module(module_path)```
module_path is `myproj.myapp.cron`
so it raise an error
the correct module_path is `myapp.cron` not `myproj.myapp.cron`
then i change crontab.py like this
```python
142: module_path=module_path.split(".",1)[1] #add this line
143: import_module(module_path)
```
it comes to work properly.

**Comment by kraiz** [comment]
Heelo @maloneguo! Seeing you running into this issue reminds me that the documentation in the readme is still based on the django 1.3 project setup where the django apps are located in the project folder not beside of it. I really should update it.

To fix this import error you should not need to change the code, just change the module path in CRONJOBS setting from:

```python
CRONJOBS = [
    ('*/5 * * * *', 'myproj.myapp.cron.task1')
]
```

to:

```python
CRONJOBS = [
    ('*/5 * * * *', 'myapp.cron.task1')
]
```

Please keep me informed if this helped you. If my suggestion proves wrong plz provide all your `django-crontab` related settings and your django version.

**Comment by kraiz** [comment]
Hopefully with the updated readme nobody traps into this again. Thanks for reporting!
