### ISSUE TITLE
Add support for different projects cronjobs

### ISSUE THREAD

**Issue by fabiocaccamo** [kraiz/django-crontab#21]
I've many projects on the same machine, each one has its own virtualenv.

If I add a cronjob for just 1 project everything works fine, but when I add a cronjob of another project it replaces the previously added cronjob.

I think the reason is that ```CRONTAB_DJANGO_MANAGE_PATH``` and ```CRONTAB_PYTHON_EXECUTABLE``` are different for each project, then there should be the possibility to specify these paths for each cronjob to avoid paths overwrite errors.

**Comment by kraiz** [comment]
hi fabio, 

there is the setting `CRONTAB_COMMENT` which is for exactly this usecase. This should default to a distinct value depending on your project's names.

It seems this does not work for you. Please set it to distinct values in your projects and try again.

**Comment by fabiocaccamo** [comment]
Great! by setting ```CRONTAB_COMMENT``` to {{project_name}}_{{virtualenv_name}} it works. So I think that there is something wrong in the ```CRONTAB_DJANGO_PROJECT_NAME``` auto-detection.

In my settings.py I also have a ```PROJECT_NAME``` variable, I think that ```CRONTAB_DJANGO_PROJECT_NAME``` auto-detection could check for that var.

My projects structure is:
```projects/{{project_name}}/{{virtualenv_name}}/```

Here I have all the virtual env stuff, my project code is located here inside a folder called sources.

**Comment by kraiz** [comment]
The `CRONTAB_DJANGO_PROJECT_NAME ` detection is based on the environment variable `DJANGO_SETTINGS_MODULE` which is set in the default project layout since the ealiest django versions and holds a project module name ([docs](https://docs.djangoproject.com/en/1.8/topics/settings/#envvar-DJANGO_SETTINGS_MODULE)). I think we should not rely on a non-django-default setting.
There can be very different project layouts especially structuring many projects side by side. Can you provide the auto-detected (maybe obfuscated) value of the setting and the environment variable for your projects?

**Comment by fabiocaccamo** [comment]
My auto-detected value is 'settings', I think the problem is here: https://github.com/kraiz/django-crontab/blob/master/django_crontab/app_settings.py#L20 , the auto-detected value is 'settings'.
Since I haven't defined CRONTAB_DJANGO_PROJECT_NAME, os.environ['DJANGO_SETTINGS_MODULE'].split('.')[0] returns 'settings'

**Comment by kraiz** [comment]
This usually works as `DJANGO_SETTINGS_MODULE` contains something like `mysite.settings` and result will be just `mysite`. This environment variable will be set explicitily in the django default project layout `manage.py`. Maybe you customized this value? Of course, then the cited "detection mechanism" will not work anymore. But there is the easy solution to this by just to set `CRONTAB_DJANGO_PROJECT_NAME ` to `mysite` and it should work again.

Did you customized the value of `DJANGO_SETTINGS_MODULE`? How does your `manage.py` look like?

**Comment by fabiocaccamo** [comment]
My projects structure is:
{project_name}/{virtualenv_name, dev, prod, etc...}/

Then here I have bin, libs, sources, etc...
The project code is inside sources.

I think that set CRONTAB_DJANGO_PROJECT_NAME manually is a good solution.
