### ISSUE TITLE
Crontab Logger issue

### ISSUE THREAD

**Issue by vineetl** [kraiz/django-crontab#22]
While the Crontab app executes as required, The logger of is not working properly. I have investigated and found that this is the comment that it shows "No handlers could be found for logger "django_crontab.crontab"" . 

Can you please tell me what, if any, changes need to be done in the settings.py of my project to solve this issue. 

Thanks

**Comment by arski** [comment]
yea, if you look at your settings.py, you'll have a `LOGGING` setting there, with a bunch of `loggers` - you'll probably have `django` and `django.request` there by default. Basically if you want logging for any other app to be pushed into your logs, you need to add that explicitly, so copy one of the loggers and replace its name with `django_crontab`. You can also add a logger with `""` as the name - that should catch logging from all apps.

**Comment by arski** [comment]
I'll assume that you solved the issue. Otherwise feel free to reopen and provide more info.

**Comment by Joshuapy** [comment]
should add `logging.basicConfig()` before `logger = logging.getLogger(__name__)`
logging.basicConfig() will add defualt Streamhandler for root  logger.
