### ISSUE TITLE
Can't add crontab jobs in my staging server

### ISSUE THREAD

**Issue by inakidelamadrid** [kraiz/django-crontab#23]
Hi guys,
this may not be an issue, but I have a great doubt on how to make the management command work in my server

I receive 
django@ip-xxxxxxxxxxx:/srv/venturefund.io/venturefund$ ./manage.py crontab add
no crontab for django
  adding cronjob: (254d9abcc1aefdee36b6b5d329edbb56) -> ('0 2 * * 2 *', 'projects.cron.weekly_activity_digest.send_digest')
  adding cronjob: (8fb9ca9f309c97b8a278ea1b49e04d2b) -> ('0 2 * * 2 *', 'django.core.management.call_command', ['set_new_investors_count'])
"/tmp/tmpFbC0M9":0: bad command
errors in crontab file, can't install.

I don't know what I did wrong. Can you help me understand what's going on?

**Comment by kraiz** [comment]
Hi, seems like there's no crontab defined before installing it with the "crontab add" management command. That's kind of good for debugging the problem. The one that is generated contains a "bad command". So let's look into the generated file...can your provide the content of the file, f.e. "/tmp/tmpFbC0M9"?

**Comment by inakidelamadrid** [comment]
Hi Krais, 
so it turned out that since I was working in MacOS, it worked with 6 fields in the crontab, but in the Ubuntu server, it is a bad syntax , only supporting 5 fields. I think we can delete this issue and I'll help you guys deal with that edge case.

**Comment by kraiz** [comment]
Wow, until now i was not aware that there's 5 and 6 field cron format. I just always used 5.
I think that should make at least into the faq.

**Comment by kraiz** [comment]
Thanks for reporting :+1:

**Comment by inakidelamadrid** [comment]
No problem, like you, I think that a little explanation in the FAQ would work for now but I'll check if I can come up with a solution and ask for a pull. Thanks for your package.
