### ISSUE TITLE
Logging jobs altogether

### ISSUE THREAD

**Issue by vahidm** [kraiz/django-crontab#24]
If you have two jobs that are running in parallel at the same time, and both of them want to write to same log file, only one of the will succeed. But in most cases you don't want to separate log file for each specific job and you want to log them altogether. I think currently `django-crontab` does not handle this situation, does it?

**Comment by kraiz** [comment]
Hi @vahidm! You're right, `django-crontab` does not handle this - but that is correct. It's the task of the operating system that is running cron. It will (or better: should) run 2 individual processes, each's stdout pointing to the same file. Depending on the exact execution start, things like context/process switching and stdout buffering the order of the jobs logging may vary, but it should be there.

I have a very bad assumption of what's maybe your problem. The README contains examples of how to configure the `CRONJOBS` setting to log the job output into a file. And in this example the `>` operator is used that overwrites the file - this is of course misleading. It should be ">>" which will append the output to the file. Did your use ">" from the example?

**Comment by kraiz** [comment]
Hopefully you got it fixed. I changed the example in the readme at least.
