### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by lucas03** [kraiz/django-crontab#27]
Yesterday Django 1.9 came out and I am still getting warnings on django_crontab. Will you support django 1.9. I believe there is just this minor fix needed.
`python/virtenv/lib/python2.7/site-packages/django_crontab-0.6.0-py2.7.egg/django_crontab/crontab.py:13: RemovedInDjango19Warning: django.uti$
  from django.utils.importlib import import_module`
Will new version of django-crontab be soon available with pip?
here is old issue - https://github.com/kraiz/django-crontab/issues/25

**Comment by kraiz** [comment]
Hey,

i prepared a branch with 1.9 support. But as this version drops support for older django versions i waited for 1.9 release. That kind of happened, yay! I'll push it to pip soon!

**Comment by kraiz** [comment]
Released to pypi as 0.7.0

```
pip install -U django-crontab
```
