### ISSUE TITLE
bad command

### ISSUE THREAD

**Issue by vinsia** [kraiz/django-crontab#29]
i can run the command 'add' in my own laptop(Mac), while i can't run it on the centos(7.0) server.
it's always show notification 'bad command'. 
ps: we are using django 1.9
                           django-crontab 0.7.0

**Comment by kraiz** [comment]
Hey, have a look in the faq section of the readme. It sounds lile you run into this, too. Please let me know, if it was this.

**Comment by vinsia** [comment]
sry, i got a task that wrote 6 parameter in the cron time field, = =|.

**Comment by kraiz** [comment]
No problem. Glad I could help ;)
