### ISSUE TITLE
Problem running crontab via run command

### ISSUE THREAD

**Issue by alexkrzyzanowski** [kraiz/django-crontab#32]
When I attempt to run job manually, I get an error:

```
MacBook-Pro-Aleksandr:beauty aperechnev$ python manage.py crontab run
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Library/Python/2.7/site-packages/django_crontab/management/commands/crontab.py", line 29, in handle
    Crontab().run_job(options['jobhash'])
  File "/Library/Python/2.7/site-packages/django_crontab/crontab.py", line 126, in run_job
    job = self.__get_job_by_hash(job_hash)
  File "/Library/Python/2.7/site-packages/django_crontab/crontab.py", line 173, in __get_job_by_hash
    'Run "python manage.py crontab add" again to resolve this issue!' % job_hash
RuntimeError: No job with hash None found. It seems the crontab is out of sync with your settings.CRONJOBS. Run "python manage.py crontab add" again to resolve this issue!
```

But the job is registered and already in sync with `django-crontab`:

```
MacBook-Pro-Aleksandr:beauty aperechnev$ python manage.py crontab show
Currently active jobs in crontab:
2755b3a03042fdf7b9c8edbcaff737f6 -> ('0 * * * *', 'grabber.cron.retrieve_new_images')
```

**Comment by kraiz** [comment]
That's supposed to happen. If you really want to test a job, give it the job id as param and run:
```
$ python manage.py crontab run 2755b3a03042fdf7b9c8edbcaff737f6
```

**Comment by alexkrzyzanowski** [comment]
Oh, thank you! I thought it runs all registered jobs :D

**Comment by kraiz** [comment]
Glad i could help on this :)

**Comment by Arbaz-Hundekar** [comment]
I have tried running with job id as said i got this error

ImportError: Import by filename is not supported

**Comment by Nour-Elgeziry** [comment]
@kraiz  hi there, just a quick issue could be due to my lack of understanding, when i run the crontab manually by running python manage.py crontab run(job id), it runs successfully but only for once although i have the settings setup to run every minute. Is there a way to make the jobs run when i run the server automatically without the need to use crontab run command

**Comment by Jinay01** [comment]
@Nour-Elgeziry Even I am facing a similar issue, did u find a solution to it?

**Comment by NathalieGomoll** [comment]
@Nour-Elgeziry @Jinay01 Hi, I'm also facing a similar issue, did one of you find a solution to it?

**Comment by rudolf-bauer** [comment]
Note, if you are using environment variables in your `CRONJOBS` declaration, the cron job needs access to them as well. E.g. the following statement will be evaluated by the `crontab add` command and the cron job. Make sure to use the same env vars.
```
CRONJOBS = [
    (os.environ.get('UPDATE_DATA_CRON_UTC', '0 3 * * *'), 'core.update_data.run', '>> /var/log/update_data.log 2>&1')
]
```
Using docker, I solved it by piping the env vars to the `/etc/environment` file in my command:
```
command: >
            bash -c "printenv >> /etc/environment && 
                           python manage.py crontab add && 
                           service cron start && 
                           python manage.py runserver 0.0.0.0:8000"
            # This is just an example, in production I strongly suggest to use a separate cron container
```

**Comment by blem14** [comment]
I've also failed to use `run` command properly and I see there still is no handling for when no hash is given after all these years.

To be fair, this issue should have been closed only after adding at least a `if job_hash is None: raise RuntimeError("No hash given")` to the code or even better parsing arguments more precisely. There's no actual example of `run` use case in the readme too and `-h` isn't really explaining anything, so I feel like arg parsing improvement would be a way to go. 😉

**Comment by DhrupamP** [comment]
> @kraiz hi there, just a quick issue could be due to my lack of understanding, when i run the crontab manually by running python manage.py crontab run(job id), it runs successfully but only for once although i have the settings setup to run every minute. Is there a way to make the jobs run when i run the server automatically without the need to use crontab run command

Any solution to this?
