### ISSUE TITLE
ImportError: No module named 'fcntl'

### ISSUE THREAD

**Issue by matthewgo** [kraiz/django-crontab#34]
Hey,

I'm quite new with Django and I'm trying to use your work for my project. I followed your steps in the documentation but I am getting the error

ImportError: No module named 'fcntl'.

Am I missing any basic step in python installation? If it matters, I'm using Windows OS.
Hope you can help!

Thanks,
Matthew Go

**Comment by kraiz** [comment]
Hi @matthewgo,

django-crontab will not work on windows as there's no crontab there, and of course no fcntl module.

Sorry :)
