### ISSUE TITLE
Daemonizing a user's CRONJOBs

### ISSUE THREAD

**Issue by socialglass** [kraiz/django-crontab#35]
Few questions -
1. Will the jobs run even after a user logs out ?
2. Do I need to add the CRONJOBs eveytime the machine reboots ? Or once added it will continue using the schedule ?
2a. How can I configure it with supervisor if need to add back everytime the machine reboots ?

**Comment by valentjedi** [comment]
1. It will
2. You don't need to do it every time. I found useful to recall `./manage.py crontab add` after you change source code of job you run.
