### ISSUE TITLE
UNIX process doesn't die after cron job is finished.

### ISSUE THREAD

**Issue by socialglass** [kraiz/django-crontab#37]
While debugging server out of memory issues on my box, it seems like the UNIX process for crontab run for my job doesn't die after the job is finished. And for the next run, a new process is spawned eventually leading to a lot of live processes for the same cron job.

My CRON settings are like this  -

```
CRONJOBS = [ ('*/1 * * * *', 'restserver.cron.my_task') ]
CRONTAB_LOCK_JOBS = True
```

The job is just a couple of log statements.

And every minute I see a new UNIX process being spawned with the same command -
`/usr/bin/python /path/to/my//manage.py crontab run aaade9ebea079cbbe06c202ef28c67d`

Is this expected ? How to make sure the process dies after the cron run instance is finished ?

**Comment by kraiz** [comment]
Can you please setup a logger for ```django_crontab``` and see of there's something?

**Comment by chika-kasymov** [comment]
I have the same issue.

In my `settings.py`:
```
CRONJOBS = [
    ('*/15 * * * *', 'dealy.coupons.cron.get_crawled_coupons', '>> /tmp/get_crawled_coupons.log 2>&1')
]
```
 
In last line of `/tmp/get_crawled_coupons.log` I have log message `error (can't fork)`. The same logs when I run command `grep CRON /var/log/syslog`.

**Comment by kraiz** [comment]
And python versions are you both using?

**Comment by chika-kasymov** [comment]
I'm using `Python 2.7.11+`. I edited my script, maybe the problem is that I didn't close some network and file connections in the end. I will check in next days if the script edit will fix my problem.

**Comment by chika-kasymov** [comment]
After changes I made everything works fine, I think the problem is not in library.

**Comment by kraiz** [comment]
Hey @socialglass, do you still have this problem? Do you handle files or sockets, too?
