### ISSUE TITLE
Jobs not being executed

### ISSUE THREAD

**Issue by heltucosta** [kraiz/django-crontab#38]
I'm sorry for making this a issue but I couldn't find any answers anywhere and no contact info for any of the contributors.

I followed the readme and was able to register my cronjobs and add my crontabs without it reporting any errors, but, no jobs are being executed. I even tried creating a log file but that's not being created also.

System:
Python 2.7.12
Django 1.8.14
django-crontab 0.7.1

**Comment by kraiz** [comment]
What's the content of your crontab? You should see it if you run ``crontab -l``.

**Comment by heltucosta** [comment]
I can see it is registered using crontab -l, but it doesn't seem to work ever.
The job I create was to just print a string to the terminal (to make sure it was working), but it never did.

**Comment by kraiz** [comment]
It will not print in your terminal if it's started by cron.

You may need to redirect the output to a file. Here is the example of the readme how to do this:
```
CRONJOBS = [
    ('0   0 1 * *', 'myapp.cron.my_scheduled_job', '>> /tmp/scheduled_job.log'),
]
```

Does that work?

**Comment by heltucosta** [comment]
No, I was already trying to log the job to a file but it's not working also. Are there any parts of my code I could post here that maybe would help ?

**Comment by kraiz** [comment]
Please post your django-crotnab settings and the output of `crontab -e`.
Did you try to run the command that has been written to crontab?

**Comment by heltucosta** [comment]
I did try to run the command using python shell and it is working.

I personally didn't change any settings of django-crontab in my settings.py file because it seems to be everything Ok.

The ouput of crontab -e is:
  GNU nano 2.5.3                                                          File: /tmp/crontab.kK05Uj/crontab                                                                                                                          

* * * * * /usr/bin/python /home/Projetos/0_Projetos/0_Onlytech/eshooter-django/manage.py crontab run 697074f372f5394f969459dcae643022 >> /tmp/scheduled_job.log # django-cronjobs for eshooter

**Comment by kraiz** [comment]
The python executable in your crontab is the system's python interpreter. Don't you use a virtualenv?
If you don't, i strongly suggest to do so because i can't help you otherwise.
If you do, we need to find out, why **django-crontab**'s `crontab add` command was writing the wrong executable to crontab. Did you have activated the virtualenv when runnning the `crontab add` command? I ask as it's intended to read the executable that it is itself started with. Maybe that didn't work in your case. Try to set the setting `CRONTAB_PYTHON_EXECUTABLE` to the python interpreter of your virtualenv, something like '~/myprojectvirtualenv/bin/python', and run `crontab add` again.

**Comment by heltucosta** [comment]
Okay, I remove all my cronjobs, activated my virtual environment and then added my cronjobs.
Now, what I get when using crontab -l is:

* * * * * /Users/heltoncosta/Sites/easy-manager/VENV/bin/python /Users/heltoncosta/Sites/easy-manager/manage.py crontab run 697074f372f5394f969459dcae643022 >> /tmp/scheduled_job.log # django-cronjobs for eshooter

Again, it doens't seem to work since my job is only printing a string and that's not appearing anywhere, not even on the log file.

**Comment by kraiz** [comment]
Ok, try to run the job in your shell. Do not activate the virtualenv.
```
$ /Users/heltoncosta/Sites/easy-manager/VENV/bin/python /Users/heltoncosta/Sites/easy-manager/manage.py crontab run 697074f372f5394f969459dcae643022
```
Does it print something to stdout (on your shell)?

**Comment by heltucosta** [comment]
Yeah, it does

**Comment by kraiz** [comment]
Ok, let's check if it's related to python/django-crontab. Run `crontab -e` and insert a new line:
```
* * * * * echo "echo output" >> /tmp/scheduled_job.log
```
This should print every minute to your file. Does this work?

**Comment by heltucosta** [comment]
Still not working, now when I crontab -l I get the following results:

* * * * * /usr/bin/python /home/Projetos/0_Projetos/0_Onlytech/eshooter-django/manage.py crontab run 697074f372f5394f969459dcae643022 >> /tmp/scheduled_job.log # django-cronjobs for eshooter
* * * * * "echo output" >> /tmp/scheduled_job.log

I run the django server but it's still not printing anything.

**Comment by kraiz** [comment]
Oh sorry. That was a misunderstanding. Please correct the `echo` command. Put another **echo** in front of your command so that its: `echo "echo output" >> /tmp/scheduled_job.log`.

What operating system do you use?

**Comment by njuaplusplus** [comment]
@kraiz 
I seem to meet a similar question.
I am using python 3, django 1.9, and django-crontab 0.7.1.
`crontab -l`  shows:

```
*/1 * * * * /usr/bin/python /tmp/test.py >> /tmp/test.log # just print('test')
*/1 * * * * echo "echo output" >> /tmp/scheduled_job.log
*/1 * * * * /usr/bin/python /DjangoProject/njuaplusplus/manage.py crontab run 0c85a22b2a84141d465ba303fa6deb18 >> /tmp/scheduled_job.log # django-cronjobs for njuaplusplus
```

Any cron job except the crontab works correctly. And if I directly run the the following in terminal, it also works as expected.

```
/usr/bin/python /DjangoProject/njuaplusplus/manage.py crontab run 0c85a22b2a84141d465ba303fa6deb18 >> /tmp/scheduled_job.log
```

I don't know how to figure it out. Also, I noticed that you said 

> If you don't, i strongly suggest to do so because i can't help you otherwise.

I wonder why you suggest so? ? Do the problem lies in the system's python interpreter?

Thanks very much.
