### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by widder** [kraiz/django-crontab#39]
Running cron with activated virtualenv using `/usr/local/www/project/venv/bin/python /usr/local/www/project/app/manage.py crontab run a2cb3e38b81be23bf313e171a630b684`
works without any error.

But in the crontab-Log there are is a FileNotFoundError

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpflqhnzil/texput.pdf'
``` 

Maybe a bug? Would be great if the cronjob in crontab behaves like when being manually executed in the virtualenv

Python 3.4
Django  1.9.8
django-crontab 0.7.1

**Comment by widder** [comment]
I'm sorry. this has nothing to do with django-crontab

**Comment by LeeKyungMoon** [comment]
How did you fix it although it is not related to django-crontab
