### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured

### ISSUE THREAD

**Issue by esseti** [kraiz/django-crontab#40]
Hello,
i'm trying to add and run a task but i've problem having it configured.
I've an enviroment and different confs that change from machine to machine.
When it runs on the server the DJANGO_SETTING_MODULE is set by the wsgi.
So, for the crontab-django i added this:

`CRONTAB_DJANGO_SETTINGS_MODULE = 'settings.ste'`

i've this job
`('* * * * *', 'rest.cron.test', ">> /tmp/out.txt")`

```
def test():
    print "echo"
```

with turns out to be

`* * * * * /Users/stefano/.virtualenvs/myv/bin/python /Users/stefano/SW/aoo-rest/dj/manage.py crontab run 524562a16a9a3585f2cf9511e5cb303d --settings=settings.ste >> /tmp/out.txt # django-cronjobs for settings`

if i run `django-admin crontab run 524562a16a9a3585f2cf9511e5cb303d` it works (but prints the output in the console)
if i paste this in the console it works (prints in the console)
it does not work when executed by cron*
in the `/var/mail/stefano` i find this every minute

```
Traceback (most recent call last):
  File "/Users/stefano/SW/rest/dj/manage.py", line 7, in <module>
    django.setup()
  File "/Users/stefano/.virtualenvs/rest/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/stefano/.virtualenvs/rest/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/Users/stefano/.virtualenvs/rest/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by esseti** [comment]
apprently the setting is not working, i ended up adding `crontab -e` this `DJANGO_SETTINGS_MODULE = settings.ste` and it works.

**Comment by kraiz** [comment]
That's a pitty as this should just work™ due to [django's docs](https://docs.djangoproject.com/en/1.10/ref/django-admin/#cmdoption--settings). Nevertheless you should be able to setup the environment variable via another `django-crontab` settings to prevent editing crontab by hand:
```
CRONTAB_COMMAND_PREFIX = 'DJANGO_SETTINGS_MODULE=settings.ste'
```

**Comment by esseti** [comment]
it should and i honestly don't know why it's not working. Maybe a mix of that and path and pythonpath. who knows.

**Comment by Fxlr8** [comment]
That happens because DJANGO_SETTINGS_MODULE is defined in wsgi.py file which is executed only by apache. If you want that variable to be set when virtualenv is activated, you should add the following line to your virtualenv's bin/postactivate file
`export DJANGO_SETTINGS_MODULE="forcepub.local_settings"`
now when cron runs your script from the virtualenv the settings module will be defined and everything should work like a charm
