### ISSUE TITLE
crontab add do nothing after manually clearing all jobs in "crontab -e"

### ISSUE THREAD

**Issue by icduicdu** [kraiz/django-crontab#41]
i run "crontab -e", clear all jobs

after that i run:
python manage.py crontab add
python manage.py crontab show

Currently active jobs in crontab:
command "python manage.py crontab show" also do nothing

**Comment by kraiz** [comment]
Does `add` print "adding cronjob..." when run? Are your jobs inserted in crontab after `add`?

**Comment by icduicdu** [comment]
Does add print "adding cronjob..." when run? - No.
Are your jobs inserted in crontab after add? - No.

**Comment by kraiz** [comment]
Please provide your configuration of the setting `CRONJOBS`.

**Comment by icduicdu** [comment]
# https://github.com/kraiz/django-crontab
# python manage.py crontab add
# python manage.py crontab show
# python manage.py crontab remove
CRONTAB_DJANGO_PROJECT_NAME = 'pr1'

PROJECT_CRONJOBS = [
    ('*/15 * * * *', 'cron_app.tasks_cron.notify_users_run'),
    ('*/10 * * * *', 'cron_app.tasks_cron.run_mail_sender'),
    ('30 * * * *', 'cron_app.tasks_cron.add_watermark_to_images'),
    ('30 * * * *', 'cron_app.tasks_cron.set_overdue'),
    ('30 * * * *', 'cron_app.tasks_cron.optimize_notifications'),
]

**Comment by icduicdu** [comment]
Sorry for you time, and thank you for your plugin :) 
It is not plugin's bug, its my...
