### ISSUE TITLE
Syntax for different scheduled jobs

### ISSUE THREAD

**Issue by waleed-hypernymbiz** [kraiz/django-crontab#44]
I have succesfully scheduled jobs that run at the start of every minute and every 5 minutes. This was accomplished by using the examples in the readme. However, when I wanted to schedule a task for the start of every hour I could not register it with cron syntax and when I added a forward slash to it it would register but NOT run. 

It would be of great help if you could add these to the examples:

Run task every hour
Run task every week
Run task at midnight
Run task monthly
Run task every year
Run task on 1 st of month
Run task on last day of month

I have searched a lot on the internet to achieve my goal but there is no help regarding this repository.

Thanks in advance.

Regard,
Waleed

**Comment by kraiz** [comment]
Hey Waleed, i agree that's something we need as it makes it easier for developers stumbling over this timing expression the first time. But i'm not sure to list all these but instead add a link to this site:
https://crontab.guru/examples.html

Please have a look at it and tell me if it would helped you.

**Comment by waleed-hypernymbiz** [comment]
Yes... These will definitely help alot in scheduling jobs for many tasks... Bookmarked!

**Comment by kraiz** [comment]
I added the link to the README. Hopefully this would help others :)

Thanks for reporting.
