### ISSUE TITLE
Django Crontab with deployment environment

### ISSUE THREAD

**Issue by LeeKyungMoon** [kraiz/django-crontab#45]
I'm developing a module with the crontab.

Actually, the framework I'm using is django so I did install ['django-crontab'][1]

  [1]: https://github.com/kraiz/django-crontab

I did test as the instruction did and make it with localhost environment.

When I deployed(`"sudo service apache2 restart"`) it on AWS after doing a command `'python manage.py crontab add'`, it didn't work.

I thiknk it's working on only localhost environment, isn't it?

How can I solve this problem?

**Comment by kraiz** [comment]
Hey, i assume using a usual (ec2?) virtual machine instance and no special aws python hosting.

- Can you run other Django management commands?
- Is there any output when you run `crontab add`?
- What's the output of `/usr/bin/crontab -l`?

**Comment by jkloving** [comment]
windows10
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\django_crontab\management\commands\crontab.py", line 4, in <module>
    from django_crontab.crontab import Crontab
  File "C:\Python27\lib\site-packages\django_crontab\crontab.py", line 3, in <module>
    import fcntl
ImportError: No module named fcntl
what's wrong???

**Comment by kraiz** [comment]
@jkloving, please don't hijack issues. Open a new one...or in your case read the [faq](https://github.com/kraiz/django-crontab#faq) where the windows-compatibility is mentioned.

**Comment by LeeKyungMoon** [comment]
@kraiz  Thank you for replying.

1) Yes I'm using ec2 on aws
2) I tested again after your reply that `'python manage.py makemigrations'` and the result had no problem
3) What I got from that command is 
`*/1 * * * * /usr/bin/python3 /home/ubuntu/MY_PROJECT_NAME/MY_PROJECT_NAME/manage.py crontab run a752d189458364014ce628a2da4654c8 # django-cronjobs for MY_PROJECT_NAME`

**Comment by kraiz** [comment]
Looks good. Try these 2 things:

- Run the command (beginning with `/usr/bin/python3 ...` copied from `crontab -l` on your terminal shell and see if it runs your code.
- What's the output of `ps aux | grep crond`?

**Comment by LeeKyungMoon** [comment]
Hm.. What does it mean first thing? I don't understand what you mean...

**Comment by kraiz** [comment]
Run `/usr/bin/python3 /home/ubuntu/MY_PROJECT_NAME/MY_PROJECT_NAME/manage.py crontab run a752d189458364014ce628a2da4654c8` as you would run other commands. This should run the the method regsitered in the CRONJOBS setting.

**Comment by LeeKyungMoon** [comment]
Actually, I'm deploying with python path as virtualenv.

So in my configuration, "python-home=/home/ubuntu/MYPROJECT/VENV" is set.

So I think it can cause the problem

**Comment by kraiz** [comment]
[Cron](https://de.wikipedia.org/wiki/Cron) is an operating system feature. Your dev and prod environment are different. `django-crontab` has many settings for which it tries to make best guesses as default values. This seems to work for your dev/localhost environment but fails on prod/aws. You need to find out what's different. I maybe can help you if you answer what i'm asking for.

Cron will just run the defined command from `crontab -l`. You should be able to just copy the generated command to your shell und run it. If you're using virtualenv (which is recommended) the python-executable `django-crontab` used to generate the command is wrong. This shouldn't have happened when you activate the virtualenv for running `crontab add`. But maybe here's the best guess problem already. There's the setting `CRONTAB_PYTHON_EXECUTABLE` to explicilty set it. But it seems you edited your last comment. Maybe it's not the problem?

What's the output of `ps aux | grep crond`? This would tell us, of the cron-service is running anyway.

**Comment by LeeKyungMoon** [comment]
Ok, I'm already trying to find it (it's hard for me , it's my first time using crontab and actually i'm in a newbie level). 

Anyway, the output of `ps aux | grep crond` is this below:
`ubuntu   12504  0.0  0.0  12916   976 pts/0    S+   12:50   0:00 grep --color=auto crond`

**Comment by kraiz** [comment]
Seems cron-service isn't running. Start it: `sudo service cron start`. This should make `ps aux | grep crond` output an additional line. This may be the reason it didn't work.

**Comment by LeeKyungMoon** [comment]
Thank you, actually I didn't know that the command for starting cron is needed.
I did command what you told and it caused no error but the output of `ps aux | grep crond
` is the same.
while I have been keeping searching to solve this problem, what I found was this command :
`sudo /etc/init.d/cron start` , and the result of this was below:
`[ ok ] Starting cron (via systemctl): cron.service.`

But sadle, the output of `ps aux | grep crond
` is the same.

**Comment by LeeKyungMoon** [comment]
Actually, the result of `'sudo service cron status'` is below:
<img width="630" alt="2016-12-19 02 33 50" src="https://cloud.githubusercontent.com/assets/7313411/21295224/c80aae6a-c593-11e6-96ae-8b869e85bba0.png">

I think it's runnign isn't it?

**Comment by kraiz** [comment]
Ahh it's systemd-based and cron service is running. As you can see in 4th last line the command has been triggered and it seems to be using your virtualenv python executable. It produced an output which has been disgarded. You should be redirecting this output to a log file by adding a third parameter in the job configuration, f.e.:
```python
CRONJOBS = [
    ('0   * * * *', 'your.app.scheduled_job', '>> /tmp/scheduled_job.log'),
]
```
Then watch `/tmp/scheduled_job.log` what's the problem.

**Comment by kraiz** [comment]
Did you find the problem?

**Comment by kraiz** [comment]
Feel free to reopen.

**Comment by pyanishjain** [comment]
@kraiz  and @leekyungmoon  thanks guys this command works

in ec2 instance we need to first run this command to start cron

`sudo /etc/init.d/cron start`
