### ISSUE TITLE
Using for Database tasks

### ISSUE THREAD

**Issue by hemangsk** [kraiz/django-crontab#46]
Hey @kraiz 
first off thanks for making this amazing utility, its great & dead simple to use.

Actually I am django-crontab for a project, my use case is, I want to fetch data from an api, every 1 hour, and save it into a database using a Django model and migration stuff. So far I've been able to write a function which fetches data, 
```
def getData():
    url = 'http://api.getdata.com/delhi' #sample url 
    r = requests.get(url)
    weather = r.json()
    data = {'weather'weather['data']}
    w_data = weathers()
    w_data.wdata = data
    w_data.save()
```
So the `data` variable is to be stored in database every 1 hour.  So I'm kinda stuck how to do this every 1 hour, 
should I add getData() in CRONJOBS in settings.py ?
This is where I'm unable to figure out how to use crontab in this use case, I'm quite new to python and django, it'll be a great help
Thanks 😄

**Comment by kraiz** [comment]
Hi, you need to define the python module path to your function. For example let's assume this project structure:

- root
  - project
    - settings.py
    - urls.py
    - wsgi.py
  - weather
    - admin.py
    - models.py
    - views.py
    - cron.py        <---- within this file is your getData function
  - manage.py
  
You need to define this in your settings.py:

```python
CRONJOBS = [
  ('0 * * * *', 'weather.cron.getData')
]
```

Then run the `add` management command to register: `python manage.py crontab add` 

After this `crontab -l` should list your task.

**Comment by hemangsk** [comment]
Hey Lars, 
Thank you so much for such a detailed response 😄  I'll try what you said.. thanks again especially the directory structure you made helped a lot in getting the complete overview.  🎉  😄

**Comment by hemangsk** [comment]
Superb! works like a charm!
