### ISSUE TITLE
django-crontab logging doesn't appear to use the default timezone

### ISSUE THREAD

**Issue by epalm** [kraiz/django-crontab#47]
Hi @kraiz, thanks for your work on this project.  I've been using django-crontab for the last year, it's simple and pretty much Just Works.  However I've noticed recently that django-crontab logging doesn't appear to use the default timezone.

settings.py
```
TIME_ZONE = 'America/Toronto' # -05:00 EST
USE_TZ = True
CRONJOBS = [
    ('0 9 * * *', 'myapp.cron.daily_order_summary', '>> cron.log'),
]
```

cron.py
```
from django.utils import timezone

def daily_order_summary():
    now = timezone.now()
    print('running daily_order_summary ({})'.format(now))
```

cron.log
```
running daily_order_summary (2017-01-11 14:00:03.304917+00:00)
```

I was expecting cron.log to be
```
running daily_order_summary (2017-01-11 09:00:03.304917-05:00)
```

Here's my server time a few minutes after running the above cron, note the "EST"
```
django@host:~$ date
Wed Jan 11 09:03:39 EST 2017
```

I'm running
- ubuntu 14.04
- django 1.8.x
- django-crontab (0.7.1)

To be clear, the cron job _runs at the correct time_, but the logging output for some reason isn't displaying the correct timezone.

**Comment by kraiz** [comment]
Hey, I think you should wrap it with `localtime()` like the [docs](https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.timezone.now) say:

> timezone.now(): 
[...]
If USE_TZ is True, this will be an aware datetime representing the current time in UTC. Note that now() will always return times in UTC regardless of the value of TIME_ZONE; you can use localtime() to convert to a time in the current time zone.

So your cron.py should look like this:

```python
from django.utils import localtime, timezone

def daily_order_summary():
    now = localtime(timezone.now())
    print('running daily_order_summary ({})'.format(now))
```

Another way would be to use django's logging which should present the log timestamps in the defined TIME_ZONE.

I didn't test both. Did that help?

**Comment by epalm** [comment]
Using `localtime` worked great.  Except in Django==1.11 and pytz==2017.2 it's

```
from django.utils import timezone
now = timezone.localtime(timezone.now())
```

Thanks for your help, @kraiz!
