### ISSUE TITLE
Example of a management command

### ISSUE THREAD

**Issue by immad-imtiaz** [kraiz/django-crontab#51]
@jiangmf @kraiz  am running a management command manually like this python manage.py check_celery_status
but unable to run it through this module. then command lies in a file under myapp.management.commands.command_file

```
class Command(BaseCommand):
    def handle(self, *args, **options):

        """
        The command to check if celery is up
        """
        date = dt.now().date()
        print str(date)
```

**Comment by kraiz** [comment]
Hey, if you want to run your command via

    python manage.py check_celery_status

it should be in `myapp.management.commands.check_celery_status`. If you can run it this way, you should be able to define this settings:

    CRONJOBS = [
        ('* * * * *', 'django.core.management.call_command', ['check_celery_status'], {}, '>> /tmp/check_celery_status.log'),
    ]

Then activate it via:

    python manage.py crontab add

...and watch `/tmp/check_celery_status.log` which should contain the output of you command.

**Comment by immad-imtiaz** [comment]
@kraiz Thanks for a quick reply just one more thing what if it has two parameters like shown below
`python manage.py get_current_currency_rate 'USD' 'PKR'`

**Comment by kraiz** [comment]
Have a look into the [docs of call_command](https://docs.djangoproject.com/en/1.11/ref/django-admin/#django.core.management.call_command), You should be able to just add more arguments after the command's name:
```python
CRONJOBS = [
    ('* * * * *', 'django.core.management.call_command', ['get_current_currency_rate', 'USD', 'PKR'], {}, '>> /tmp/get_current_currency_rate.log'),
]
```
I didn't test it thouh.
