### ISSUE TITLE
is django-crontab still in active development?

### ISSUE THREAD

**Issue by asi14** [kraiz/django-crontab#55]
I'm interested in implementing this app on my django app (mainly because of immense difficulties using native crontab) -- is it still in active development?

**Comment by kraiz** [comment]
Let's call it feature complete and stable. I'm still here watching to keep it compatible with upcoming django versions.

**Comment by zhouxiaoqi** [comment]
Why can not use the above windows?

**Comment by Ronaldomata34** [comment]
django-crontab is it working in production? can run on heroku?

**Comment by kraiz** [comment]
Sorry, no windows-support because windows doesn't have cron.

And also no cron on Heroku. I suggest going for their [Scheduler Addon](https://devcenter.heroku.com/articles/scheduler) and [Django Management Commands](https://docs.djangoproject.com/en/dev/howto/custom-management-commands/).

**Comment by kraiz** [comment]
I just updated to build/test matrix in #75. Tests include Django 1.8 - 2.0 with Python 2.7, 3.3 - 3.6. As there were no code changes necessary, I'll keep `django-crontab` on `0.7.1`.
