### ISSUE TITLE
ImportError: Import by filename is not supported

### ISSUE THREAD

**Issue by Arbaz-Hundekar** [kraiz/django-crontab#56]
When i call ->
python manage.py crontab run job_id, I got the above error

**Comment by madzohan** [comment]
You have to specify it in python module dot notation (without `/` slashes etc)
`CRONTAB_DJANGO_SETTINGS_MODULE = 'main.my_cool_package.settings'`

**Comment by kraiz** [comment]
You need to provide more context. How does your `django-crontab`-settings look like? Did you run `python manage.py crontab add`? What's the output of `crontab -l` after `add`?
