### ISSUE TITLE
Django crontab with aws elastic beanstalk

### ISSUE THREAD

**Issue by ryeonghwi** [kraiz/django-crontab#57]
My crontab job is running fine on development. I just cannot make it work on aws elastic beanstalk.

**Comment by kraiz** [comment]
`django-crontab` relies on the usual linux `cron`-service. Please make your it's available within your environment.

My first [google result](https://aws.amazon.com/de/premiumsupport/knowledge-center/cron-job-elastic-beanstalk/) shows up some infos and i doubt `django-crontab` is helpful. I recommend reading this document, wrap your scripts into django management commands and write them into `.ebextensions/conjob.config` by hand.
