### ISSUE TITLE
why do I have to run `crontab add` twice when settings changed?

### ISSUE THREAD

**Issue by madzohan** [kraiz/django-crontab#58]
How it could be resolved per one `crontab` management command call?

**Comment by kraiz** [comment]
Please provide more context: your crontab settings and the output of `crontab -l` before and after each `add`.

**Comment by kraiz** [comment]
Hey @axper, seems you changed `CRONJOBS` content (`'extract_zi'` => `'extract_zip'`). That's the reason why the parameter after `crontab run` inside `crontab -l` changed. As mentioned in the README you need to always `add` after changing the `CRONJOBS` settings. This is expected behavior.

**Comment by axper** [comment]
@kraiz Yes, that was my intention. My problem is I want to have 7 such scripts in my crontab. And every time I change them, I have to run `python mange.py crontab add` 8 (eight) (!) times. This makes my deployment scripts very ugly.It would be very helpful if 1 simple

**Comment by madzohan** [comment]
Thats how looks like my deployment script 🚶 
```
# the same command twice to replace existing cronjob (https://github.com/kraiz/django-crontab/issues/58)
    manage_api crontab add
    manage_api crontab add
```

**Comment by axper** [comment]
@madzohan That is exactly what I do *not* want to do, as for `n` jobs `n+1` `add` commands are required currently to work properly.

@kraiz Please reopen?

**Comment by simonbru** [comment]
@axper
I noticed that this error occurs when the command tries to display which cron tasks get remove (i.e. `removing cronjob: XXX -> XXX`.

The `add` command works fine when setting the verbosity to 0 (i.e. `./manage.py crontab -v0 add`). All obselete cron tasks get removed or replaced by their current version with only one `add` call.

@kraiz 
I think it would be nicer to keep the same behavior independently of the verbosity.
