### ISSUE TITLE
Seems `crontab` doesn't save Django PATH on `crontab add` call 

### ISSUE THREAD

**Issue by madzohan** [kraiz/django-crontab#59]
```
CRONTAB_COMMAND_PREFIX = "echo 'cd {} && . venv/bin/activate &&".format(
    config['pkg_path'])
```
Why do I have to run `cd` in PREFIX when I specified absolute path to `manage.py` `CRONTAB_DJANGO_MANAGE_PATH` ? I think it should be _saved_ on `crontab add` step

**Comment by kraiz** [comment]
Hm, you shouln't need to as it tries to find absolute paths for executable and manage.py. A `cd` step should not be necessary. How does not crontab looks like after `add`ing?
