### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by brayan15** [kraiz/django-crontab#60]
I defined my task, but doesn't want show, I added a simple code:
def my_scheduled_job():
   #your functionality goes right here
   print('hello')

and on setting I putted this: 
CRONJOBS = [
    ('*/2 * * * *', 'vehicle_control_system.persons.contrab.my_scheduled_job'),
]

but first I ran python manage.py contrab add and later I run django with python manage.py runserver

**Comment by kraiz** [comment]
Ok and what's the problem?

**Comment by brayan15** [comment]
the output was this:
*/2 * * * * /Users/brayanlara/virtualenvs/vehicle/bin/python /Users/brayanlara/Desktop/Projects/vehicle_control_system/manage.py crontab run b11ab998cc14f55a4642db8bfd678835 # django-cronjobs for config

**Comment by addisonlynch** [comment]
vehicle_control_system.persons.contrab -> vehicle_control_system.persons.crontab?

**Comment by brayan15** [comment]
not, because my file called contrab and als I run python manage.py. crontab add later python manage.py runserver, but never doesn't show print

**Comment by kraiz** [comment]
Sure...as the command will be called from a system service not from within your shell. If you're interested in the stdout stream you should redirect it into a logfile. It's documeted in the README, have a look at example 1 on settting CRONJOBS.

**Comment by brayan15** [comment]
ty, I'm going to review

**Comment by mhoonjeon** [comment]
@kraiz I'm having the same trouble. I can `add` and `run` cronjob, but if I `python manage.py runserver` to see if django-crontab is actually doing my scheduled jobs(`=scheduled_crawl` to create CrawlLogfor testing purposes), nothing happens. I tried redirecting it into logfile like you suggested, but it's not working too. 

`settings.py`
```python
import os


CRONJOBS = [
    ('* * * * *', 'crawlers.cronjobs.scheduled_crawl', '>> /crawllog.log'),
]
```
`crawlers.cronjobs.py`
```python
from .models import CronLog


def scheduled_crawl():
    CronLog.objects.create()
```
`crawlers.models.py`
```python
from django.db import models

class CronLog(models.Model):
    date = models.DateTimeField(auto_now_add=True, blank=True)

    def __unicode__(self):
        return self.date.ctime()
```


I'm using django within pyenv environment. Any ideas what it is not working?

**Comment by mhoonjeon** [comment]
@brayan15 @kraiz 
I managed to figure out the solution. Apparently, crontab does not automatically pick up local virtual environment's(=pyenv in my case) environment variables. So you have to set them manually using `crontab -e` command.

After setting the following 4 environment variables in `crontab -e`, crontab started working as expected.
```python
DJANGO_SETTINGS_MODULE=core.settings.development
DATABASE_URL=postgres://my_id:my_password@localhost:5432/my_db_name
DJANGO_SECRET_KEY=my_django_secret key
PATH=~/.pyenv/shims:~/.pyenv/bin:"$PATH"

*/1 * * * * /Users/mhjeon/.pyenv/versions/3.6.0/envs/djangocrawler/bin/python /Users/mhjeon/projects/djangocrawler/manage.py crontab run b9a4006b4087d6494c1b442bcadb1db0 >> /tmp/scheduled_job.log # django-cronjobs for core
```

I guess this probably should be added to *doc* or *REAME*, for I have spent more than 5 days searching for the right answer in futile. I owe getting the hint about environment variables to [this blog, which in Korean](http://throughkim.kr/2016/04/06/crontab-pyenv/).

*Note*: I'm yet to test this solution on live, on AWS EBS. I only tested on local development settings. But I presume if you set those environment variables correctly, I should work on remote servers also.

**Comment by kraiz** [comment]
Hi @mhoonjeon, that's kind of strange. `django-crontab` writes the python interpeter (or virtualenv) used to run the `add` subcommand into cronjob which seems to work fine for you.

It seems `pyenv` really need this PATH changes to actually work. Can you please assist and remove just the PATH line. If it's not working then, we double checked it and i'll add a `pyenv`-hint into the FAQ section of the README.

**Comment by clock21am** [comment]
can you tell me what is the exactly that path is point to...I am getting the similiar issue

**Comment by chirag-jn** [comment]
I usually add the following variables in `crontab -e` and things seem to be moving:
```bash
SHELL=/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin
```
