### ISSUE TITLE
log stderr?

### ISSUE THREAD

**Issue by allthetime** [kraiz/django-crontab#61]
Hi, I'm wondering if there is a simple way to log stderr?

Recently discovered a cronjob that was silently failing for a few weeks and caused some headaches and would like to avoid this in the future.

**Comment by kraiz** [comment]
Hey, have a look into the README for the setting `CRONTAB_COMMAND_SUFFIX` and try to set it to the mentioned  example value. This will redirect the stderr stream to stdout which already capture into a logfile?

**Comment by allthetime** [comment]
I don't want to mix the two streams as output logs are important as well and I want to set-up a watch on the error log so that I can send email alerts to devs. I suppose I could just do some parsing on the output log. But, do you think it would be relatively easy to modify this library to allow such functionality? I would consider doing it myself if it's not too much trouble.

**Comment by kraiz** [comment]
I think you could redirect stderr into another file:
```
CRONJOBS = [
    ('* * * * *', 'myapp.cron.my_scheduled_job', '>> stdout.log 2>>stderr.log')
]
```

**Comment by allthetime** [comment]
@kraiz Oh sweet, thank you for your help. I didn't know that was possible with bash!
