### ISSUE TITLE
Cron doesn't work?

### ISSUE THREAD

**Issue by MTeres** [kraiz/django-crontab#62]
#### Environment & Versions
* Operating system: Linux
* Python: 3.6.1
* Django: 1.11.4
* django-crontab: 0.7.1

#### Settings
* My `django-crontab` settings: 
```python
CRONJOBS = [('* * * * *', 'core.enquetes.cron.func')]
```

#### Details
`/usr/src/app# python manage.py crontab show
Currently active jobs in crontab:
cde74bdd655f575c043ed27d9c7da793 -> ('* * * * *', 'core.enquetes.cron.func')`

```
crontab -l
* * * * * /usr/local/bin/python3 /usr/src/app/manage.py crontab run cde74bdd655f575c043ed27d9c7da793 # django-cronjobs for base
```
`python manage.py crontab run cde74bdd655f575c043ed27d9c7da793` (inside docker container) - WORK

But the automatic version dosent work ;/

**Comment by kraiz** [comment]
Hey, there's no cron service running within your container, if you don't start it yourself.
Have a look at [these issues](../issues?q=docker) and maybe read about [cron and docker](https://google.com/search?q=docker+cron+background).

Closing this as it's not a `django-crontab` issue.
