### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by jy95** [kraiz/django-crontab#63]
#### Environment & Versions
* Operating system: Linux (XUbuntu 16 TLS)
* Python: 2.7
* Django: 1.11.3
* django-crontab: 0.71

#### Settings
* My `django-crontab` settings: 
```python
CRONJOBS = [
    ('* * * * *', 'student_collaboration.cron.set_open_help_request_to_pending'),
    ('* * * * *', 'student_collaboration.cron.close_pending_help_requests_automatically_when_expired'),
]
```

#### Details

When I run `python manage.py crontab add`
```
  adding cronjob: (7931e4f0fc70fdb88ed51de09299094a) -> ('* * * * *', 'student_collaboration.cron.set_open_help_request_to_pending')
  adding cronjob: (da9d5e4cf8f5753ba16b9f786fd864b8) -> ('* * * * *', 'student_collaboration.cron.close_pending_help_requests_automatically_when_expired')
```

* Output of `crontab -l` after running `python manage.py crontab add`.
```
* * * * * /home/jy95/Documents/oscareducation/ve/bin/python /home/jy95/Documents/oscareducation/manage.py crontab run 7931e4f0fc70fdb88ed51de09299094a # django-cronjobs for oscar
* * * * * /home/jy95/Documents/oscareducation/ve/bin/python /home/jy95/Documents/oscareducation/manage.py crontab run da9d5e4cf8f5753ba16b9f786fd864b8 # django-cronjobs for oscar
```

My projet tree:
```
/oscar (the main app)
       settings.py (where the crontab schedule are set)
/student_collaboration (sub app)
      cron.py (where the cron function are defined)
```

The github repo : https://github.com/JonathanSamelson/oscareducation/tree/prototype_2

**Comment by breneser** [comment]
I second that, I am running it in a docker container. Connection to container and running `python manage.py crontab show` shows the task but it is not triggered.

**Environment & Versions**

Docker image based on python3 latest (https://github.com/docker-library/python/blob/cf179e4a7b442b29d85f521c2b172b89ef04beef/3.6/jessie/Dockerfile) (which is Ubuntu Jessie)

Django: 1.11.4
django-crontab: 0.71

**Settings**
```
CRONJOBS = [
    ('* * * * *', 'django.core.management.call_command', ['export'], {}, '>> /tmp/export.log'),
]
```

`crontab -l` output:
```
* * * * * /usr/local/bin/python3 /code/manage.py crontab run 349a9989dffe1f33c49e95a987f2d95d >> /tmp/export.log # django-cronjobs for ..
```

**Comment by jy95** [comment]
Was a issue on my virtual machine : it works
