### ISSUE TITLE
Can't get the cron to run properly

### ISSUE THREAD

**Issue by DibPuelma** [kraiz/django-crontab#64]
#### Environment & Versions
* Operating system: macOS Sierra 10.12.5
* Python: 3.6.1
* Django: 1.11.1
* django-crontab: 0.7.1

#### Settings
* My `django-crontab` settings: 
```python
CRONJOBS = [
  ('*/1 * * * *', 'indicei3.cron.test_cron', '>> /tmp/scheduled_job.log')
]
```

#### Details
* Output of `crontab -l` after running `python manage.py crontab add`.
```
  adding cronjob: (14916de3431e91ed32d3691cfe1be719) -> ('*/1 * * * *', 'indicei3.cron.test_cron', '>> /tmp/scheduled_job.log')

```
* If this output contained a `crontab run` command and I copy this command to my terminal the job works: yes/no

No

I have been searching for a solution for some hours now but I couldn't find anything

This is my cron.py:
```python
def test_cron():
    print("Hello")
```
I start the server but nothing happens. The file under tmp/schedule_job.log does not get written.

Thanks in advance.

**Comment by ArthurRyan** [comment]
you should use print method. It doesn't fit the source code I think.

**Comment by kraiz** [comment]
Sorry for the delay. Please run this command: `cronrab -l`. What does it print? There should be something with `django-crontab` after running the `crontab add` command.

**Comment by ghost** [comment]
Hello @kraiz, I got the same errors.

`crontab -l`
output => `*/1 * * * * /usr/local/opt/python@3.9/bin/python3.9 /Users/user/Desktop/Projects/project/manage.py crontab run 38e45ce47d0c4b4f1b31ce3fe289a4bc >> /tmp/scheduled_job.log # django-cronjobs for main`

It presents in active list job but it's never run, anyway if I run `/usr/local/opt/python@3.9/bin/python3.9 /Users/user/Desktop/Projects/project/manage.py crontab run 38e45ce47d0c4b4f1b31ce3fe289a4bc >> /tmp/scheduled_job.log` direct on terminal it worked.

**Comment by RussellLuo** [comment]
I encountered a similar issue, but later realized that I had been looking at the wrong place. On macOS, the correct command for checking the crontab output should be:

```bash
tail -f /var/mail/{username}
```
