### ISSUE TITLE
django-crontab can not not run friendly with  multiprocessing

### ISSUE THREAD

**Issue by liulp** [kraiz/django-crontab#68]
The django-crontab's function  likes this:

def f(x):
    print x

def fun():
    pool = multiprocessing.Pool(processes=4)
    for i in range(1,10):
        pool.apply_async(f, (i,))
    pool.close()

The  fun is the django-crontab's function  ，when I run it ，it can not  run  friendly

**Comment by kraiz** [comment]
What's the problem and do you mean by friendly?

**Comment by liulp** [comment]
The function  likes this:
`
import  multiprocessing
def f(x):
    print x

def host_alarm():
    pool = multiprocessing.Pool(processes=4)
    for i in range(1,10):
        pool.apply_async(f, (i,))
    pool.close()
`
------------------------------------------------------------------------------------
AND the crontab likes this :
`
CRONJOBS = [
    ('*/1 * * * *', 'monitor.crontab.host_alarm', '>>/var/log/ocean.log')
]
`
-------------------------------------------------------------------------------------------------
when I  run the crontab , I can not get  the  result which I want “1 2 3 4 5 6 7 8 9”.  It only shows  the result   “1” .

**Comment by kraiz** [comment]
Please format your code. I cannot see correct intention levels.

I assume you're closing the processing pool before it had the chance to process all functions.

**Comment by liulp** [comment]
The function likes this:
```python
def f(x):
    print x

def fun():
    pool = multiprocessing.Pool(processes=4)
    for i in range(1,10):
        pool.apply_async(f, (i,))
    pool.close()
```
AND the crontab likes this :
```python
CRONJOBS = [ ('*/1 * * * *', 'monitor.crontab.fun', '>>/var/log/ocean.log') ]
```

Now ,I have found out the reason for the problem。 Thank you very much。
I  can not  take “pool.join()”  as the end. When  I add  it , it runs ok.

The fun  likes this:
```python
def f(x):
    print x

def fun():
    pool = multiprocessing.Pool(processes=4)
    for i in range(1,10):
        pool.apply_async(f, (i,))
    pool.close()
    pool.join()
```
The  end， Thank you very much！
