### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by rtv313** [kraiz/django-crontab#70]
#### Environment & Versions
* Operating system: WINDOWS 10
* Python: 3.5
* Django: 2.0

#### Details
File "C:\Users\Usuario\Documents\VenvDinamicPub\ENV\lib\site-packages\django_crontab\crontab.py", line 3, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by PabloLefort** [comment]
@rtv313 before you make the import, can you show the output of: 
```python
import sys
print(sys.version)
```

**Comment by kraiz** [comment]
Hey, as mentioned in the FAQ section of the readme....there's no windows support as windows lacks cron.

**Comment by mohammad-alqudah** [comment]
welcome !
