### ISSUE TITLE
python manage.py crontab remove clearn all infos from crontab file

### ISSUE THREAD

**Issue by sshaplygin** [kraiz/django-crontab#82]
#### Environment & Versions
* Operating system: Ubuntu 
* Python: 3.5.2
* Django: 1.11
* django-crontab: 0.7.1

#### Settings
* My `django-crontab` settings: 
```python
CRONJOBS = [
  ...
]
```

#### Details
* Output of `crontab -l` after running `python manage.py crontab add`.
```
I use `python manage.py crontab remove clearn`
...
```
* If this output contained a `crontab run` command and I copy this command to my terminal the job works: yes/no

**Comment by kraiz** [comment]
Hey, I don't exactly understand what's the problem. The `remove` sub-command don't expect any argument. You should be able to remove any previously added job with `python manage.py crontab remove`.

**Comment by sshaplygin** [comment]
@kraiz It is not a bug, it is a feature 👍. But in docs i don't see this informations.

> The remove sub-command don't expect any argument. You should be able to remove any previously added job with python manage.py crontab remove.

If you have some experience on JavaScript/Python remove's function worked different your implementation and unclear for me or may be some people.

Thanks for discussion and good luck.

**Comment by kraiz** [comment]
This is no list manipulation withon source code...it's a cli command. I'm sure it's mentioned within cli command's help section and the project's readme. Nevertheless, glad I could help.
