### ISSUE TITLE
Log file can't write encode other characters 

### ISSUE THREAD

**Issue by iHTCboy** [kraiz/django-crontab#93]
#### Environment & Versions
* Operating system: macOS 10.14.1
* Python: 3.6
* Django: 2.0.6
* django-crontab: 0.7.1

#### Settings
* My `django-crontab` settings: 
```python
CRONJOBS = [
        ('*/1 * * * *', 'SchedulerTask.views.AutoSubmit', '>> /Destop/task.log'),
]
```

#### Details
user print other characters， error:
```
'ascii' codec can't encode characters in position 685-689: ordinal not in range(128)
```

Can I only encode the contents of each output？

**Comment by pawan-betrics** [comment]
please use print statement inside you function, because here logger lib not working.
